version: '3'

services:
   db:
     image: mariadb_utf8
     volumes:
       - account_manage_db:/var/lib/mysql
     restart: always
   web:
     depends_on:
       - db
     image: .
     ports:
       - "8000:8000"
     restart: always
volumes:
    account_manage_db:
