version: "3"

services:
  db:
    build: ./mariadb/
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/sql:/docker-entrypoint-initdb.d
      - v_account_manage_db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=negaposi
      - MYSQL_USER=negaposi_user
      - MYSQL_PASSWORD=negaposi_pass_db

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./src:/src"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0
    restart: always

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=negaposi_user
      - PMA_PASSWORD=negaposi_pass_db
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  v_account_manage_db:
    driver: local
