use negaposi;
CREATE TABLE `TBL_STUDENT_COMMENTS` (  
`STUDENT_ID` int(3) NOT NULL COMMENT '生徒ID',
`LABO_ID` int(3) NOT NULL COMMENT '研究室ID',
`YEAR` int(4) NOT NULL COMMENT '年度',
`COMMENTS` text DEFAULT NULL COMMENT '感想',
PRIMARY KEY (`STUDENT_ID`,`LABO_ID`,`YEAR`)) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `TBL_LABO` (  
`LABO_ID` int(3) NOT NULL,
`LABO_NAME` text NOT NULL,
PRIMARY KEY (`LABO_ID`)) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO TBL_STUDENT_COMMENTS VALUES(1, 1, 2019, 'おもろいわあんた。');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(2, 2, 2019, 'うまい！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(3, 3, 2019, 'くそがあ！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(4, 4, 2019, '睡眠気持ちー！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(5, 5, 2019, '寝坊したわ30分！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(6, 6, 2019, 'あーもぉ！！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(7, 7, 2019, 'うるせえ！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(8, 8, 2019, '善逸かっこいい！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(9, 9, 2019, '禰豆子かわいい！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(10, 10, 2019, '炭治郎えらい！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(11, 1, 2020, '伊之助こわい！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(12, 2, 2020, '判断が遅い！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(13, 3, 2020, '判断が早い！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(14, 4, 2020, '疲れない呼吸法！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(15, 5, 2020, 'ながまがお！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(16, 6, 2020, 'あかともならなんでもできる！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(17, 7, 2020, '正座でかい！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(18, 8, 2020, 'ストロングゼロ２本同時飲み！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(19, 9, 2020, '水の呼吸　壱ノ型　水車！ながまがお！');
INSERT INTO TBL_STUDENT_COMMENTS VALUES(20, 10, 2020, '僕たちは燃え盛る旅の途中で出会い。');
INSERT INTO TBL_LABO VALUES(1, 'あーも研究所');
INSERT INTO TBL_LABO VALUES(2, 'ながお研究所');
INSERT INTO TBL_LABO VALUES(3, 'まがお研究所');
INSERT INTO TBL_LABO VALUES(4, 'いつき研究所');
INSERT INTO TBL_LABO VALUES(5, 'きたくま研究所');
INSERT INTO TBL_LABO VALUES(6, 'ほくりゅう研究所');
INSERT INTO TBL_LABO VALUES(7, 'ひらい研究所');
INSERT INTO TBL_LABO VALUES(8, 'こーら研究所');
INSERT INTO TBL_LABO VALUES(9, 'かつどん研究所');
INSERT INTO TBL_LABO VALUES(10, 'ようかん研究所');
